### PR TITLE
Logon

### PR DESCRIPTION
**Pull request by estherho527**
logon branch was created in case the look from front branch was preferred. But I think logon branch has the updated backend files from the master branch, and the front end files we turned in yesterday for phase I. DatePickerPanel is no longer needed.  I originally used it for the EmployeeGUI.java class, but now added the code directly inside it.  

Are we ready to merge them?

### CODE REVIEW

**Comment by klotfian** [comment]
I'm a bit confused right now as to which branch is our main branch after
the recent merging. I also noticed that Ari hasn't updated the system class
to what we agreed upon last night. If anyone can clear things up for before
I start adding the date functions, that would be really helpfull thanks a
bunch.

**Comment by estherho527** [comment]
Okay, so from what I can see, the only difference b/w master and logon
branch is the BasicDemo, which we no longer need.

So to clean things up, why don't we:

   - make the master branch our default branch again
   - remove BasicDemo.java
   - THEN delete the logon branch

Moving on then, Ari and I can use the front branch to upload Phase2
changes, and Kamran can use a separate NEW back branch to upload Phase2
changes.  When we agree and get everything how we want it, we can merge the
two branches to the master one.

How does this sound?

-Esther

**Comment by klotfian** [comment]
I'm okay with all that but I don't think creating a new branch just for
backend is really neccessary, since only the doctor and system class will
be updated. That's why after making master branch the default, deleting
basicdemo.java and logon branch, I would just update system and add
staff.java while deleted doctor.java

**Comment by estherho527** [comment]
All right, that works too.

Kamran, can you make the master branch the default one? I think since the
project is under your account, you have the option to change those settings.

**Comment by klotfian** [comment]
done

**Pull request merged**
